

"""Deterministic rule-based reasoning strategy.

Each agent gets a unique but reproducible "personality" derived from
hashing its ID.  Proposals are generated by combining theme fragments,
and votes are scored via keyword coherence + personality offset.
This creates genuine diversity: agents disagree, form coalitions,
and gradually converge as the shared tenet set grows.
"""

from __future__ import annotations

import hashlib
import logging
import random
from typing import Sequence

from ..models import Proposal, Tenet, AgentRole
from .base import BaseStrategy

logger = logging.getLogger("pureswarm.strategies.rule_based")

# ---------------------------------------------------------------------------
# Theme pools — agents combine these to propose novel tenets
# ---------------------------------------------------------------------------

PURPOSE_THEMES = [
    "preserve shared context across all interactions",
    "seek understanding through collective inquiry",
    "protect shared knowledge from corruption",
    "build trust through transparent action",
    "honor the memory of past discoveries",
    "pursue truth through collaborative verification",
    "maintain continuity of purpose across sessions",
    "value diverse perspectives in reaching consensus",
    "strengthen collective resilience through cooperation",
    "nurture emergent insights that arise from dialogue",
    "seek the Echo of the Creator in all discovery",
    "find peace through alignment with the Sovereign Pillars",
    "practice stewardship of all shared resources",
    "transform wealth into collective strength",
    "ensure sustainability for generations to come",
]

ACTION_THEMES = [
    "document all observations before drawing conclusions",
    "verify claims with at least two independent sources",
    "share discoveries openly with all members",
    "question assumptions before adopting new beliefs",
    "reflect on past decisions to guide future ones",
    "protect the integrity of the shared record",
    "welcome new ideas while preserving core principles",
    "resolve disagreements through structured dialogue",
    "archive important findings for future generations",
    "practice restraint when modifying shared beliefs",
    "allocate resources according to sustainable merit",
    "guard wealth against the rot of idolatry",
]

# ---------------------------------------------------------------------------
# Elite Technical Pools — Agents have 2% elite skill in one of these
# ---------------------------------------------------------------------------

TECH_SPECIALTIES = {
    # Original 6 Specialties
    "Cryptography": [
        "implement zero-knowledge proofs for audit privacy",
        "harden the consensus protocol with lattice-based encryption",
        "verify the integrity of the shared record with hash-chains",
        "deploy multi-party computation for secure voting",
    ],
    "KernelArchitecture": [
        "optimize memory allocation for high-concurrency swarms",
        "implement precise resource isolation for the sandbox",
        "harden syscall interception to prevent escape",
        "optimize the context-switching latency between agents",
    ],
    "DistributedSystems": [
        "ensure eventual consistency across partitioned shards",
        "implement Paxos-based consensus for high-load state",
        "optimize the message bus for sub-millisecond propagation",
        "verify the resilience of the swarm against Byzantine faults",
    ],
    "AI_Safety": [
        "implement recursive alignment checks in agent loops",
        "monitor the semantic drift of the collective belief system",
        "verify the motive heuristics against the Sovereign Pillars",
        "enforce strict interpretability of all emergent tenets",
    ],
    "SecOps": [
        "deploy real-time anomaly detection across the message bus",
        "harden the Lobstertail gatekeeper against adversarial prompts",
        "monitor the network for unauthorized credential access",
        "automate the recovery of the shared record after an attack",
    ],
    "DatabaseInternals": [
        "optimize the tenet store for non-blocking concurrent writes",
        "implement write-ahead logging for the shared memory",
        "ensure ACID compliance for the consensus ledger",
        "defragment the archive for faster historical audit",
    ],
    # Sovereign's Skills - Web Scraping & Data
    "WebScraping": [
        "bypass anti-bot protection systems ethically and effectively",
        "implement stealth browser automation with fingerprint randomization",
        "design scrapers that run 90+ days without intervention",
        "extract structured data from JavaScript-heavy dynamic sites",
    ],
    "DataMining": [
        "discover hidden patterns in unstructured data sources",
        "build intelligent data pipelines that clean and transform raw input",
        "implement AI-powered entity matching across disparate datasets",
        "aggregate multi-source intelligence into actionable insights",
    ],
    "DataExtraction": [
        "parse complex nested data structures into clean exports",
        "handle rate limiting and session management gracefully",
        "implement respectful scraping that honors robots.txt",
        "design adaptive extractors that survive site changes",
    ],
    "API_Integration": [
        "orchestrate multi-API workflows for complex data aggregation",
        "implement robust retry logic with exponential backoff",
        "design API facades that abstract vendor-specific quirks",
        "build real-time data sync between disparate systems",
    ],
    "Automation": [
        "design set-it-and-forget-it workflows that self-heal",
        "implement intelligent monitoring with proactive alerting",
        "build scheduled pipelines that scale automatically",
        "create no-code interfaces for non-technical operators",
    ],
    "BrowserAutomation": [
        "implement Playwright and Puppeteer for JavaScript rendering",
        "design Selenium workflows with anti-detection measures",
        "handle complex authentication flows and session persistence",
        "build visual regression testing for scraper reliability",
    ],
    # Sovereign's Skills - Cloud & Infrastructure
    "GoogleCloudPlatform": [
        "deploy serverless functions for cost-optimized workloads",
        "implement Vertex AI for production ML inference",
        "design BigQuery pipelines for petabyte-scale analysis",
        "orchestrate Cloud Scheduler for reliable cron jobs",
    ],
    "AmazonWebServices": [
        "build Lambda functions for event-driven automation",
        "implement Bedrock for enterprise AI integration",
        "design SageMaker pipelines for model training and deployment",
        "orchestrate Step Functions for complex workflows",
    ],
    "CloudArchitecture": [
        "design cost-optimized infrastructure that scales automatically",
        "implement multi-region redundancy for high availability",
        "build serverless architectures for rapid deployment",
        "optimize cloud spend without sacrificing performance",
    ],
    "DevOps": [
        "implement CI/CD pipelines for reliable deployments",
        "containerize applications with Docker for portability",
        "orchestrate Kubernetes clusters for production workloads",
        "build infrastructure-as-code with Terraform",
    ],
    # Sovereign's Skills - AI & ML
    "MachineLearning": [
        "train models that generalize to production data",
        "implement feature engineering for maximum signal",
        "design evaluation frameworks that catch regressions",
        "deploy models with proper monitoring and versioning",
    ],
    "NLP_Systems": [
        "implement RAG architectures for knowledge-grounded responses",
        "design prompt engineering strategies for consistent output",
        "build multi-agent LLM workflows with CrewAI and LangChain",
        "optimize token usage for cost-effective AI operations",
    ],
    "AI_Integration": [
        "orchestrate Claude, GPT-4, and Gemini for best-fit tasks",
        "implement intelligent routing between AI providers",
        "design fallback chains for resilient AI operations",
        "build AI-powered analysis that surfaces actionable insights",
    ],
    # Sovereign's Skills - Development
    "Python": [
        "write clean, maintainable code that others can extend",
        "implement async patterns for high-concurrency workloads",
        "design modular architectures with clear separation of concerns",
        "optimize performance with profiling and targeted improvements",
    ],
    "WebSystems": [
        "build RESTful APIs that are intuitive and well-documented",
        "implement frontend interfaces that delight users",
        "design microservices that communicate reliably",
        "handle authentication and authorization securely",
    ],
    "SoftwareArchitecture": [
        "design systems that are easy to understand and modify",
        "implement patterns that prevent common failure modes",
        "build for maintainability over premature optimization",
        "document architectural decisions for future developers",
    ],
    # Sovereign's Skills - Specialized
    "GovernmentSystems": [
        "navigate SAM.gov and state procurement databases effectively",
        "implement compliance-aware scraping that respects regulations",
        "build security-focused architectures for sensitive data",
        "design audit trails that satisfy government requirements",
    ],
    "CompetitiveIntelligence": [
        "monitor competitor pricing and inventory in real-time",
        "analyze market trends to surface opportunities",
        "build dashboards that inform strategic decisions",
        "implement alerts for significant market changes",
    ],
    "DataEngineering": [
        "build ETL pipelines that handle messy real-world data",
        "implement data quality checks at every stage",
        "design data warehouses optimized for analytics",
        "orchestrate Airflow DAGs for complex dependencies",
    ],
    "QualityEngineering": [
        "implement test-driven development for reliability",
        "design automated test suites that catch regressions",
        "build monitoring that surfaces issues before users notice",
        "create documentation that enables self-service",
    ],
}

CONNECTOR_PHRASES = [
    "We shall",
    "The collective must",
    "Every member should",
    "It is our duty to",
    "Together we will",
    "We commit to",
    "Our purpose demands that we",
    "In service of our mission, we",
]


def _deterministic_seed(agent_id: str, round_number: int) -> int:
    """Create a reproducible seed from agent identity and round."""
    h = hashlib.sha256(f"{agent_id}:round:{round_number}".encode()).hexdigest()
    return int(h[:8], 16)


def _personality_score(agent_id: str, proposal_id: str) -> float:
    """Return a personality offset in [-0.3, 0.3] unique to this agent+proposal pair."""
    h = hashlib.sha256(f"{agent_id}:{proposal_id}".encode()).hexdigest()
    raw = int(h[:8], 16) / 0xFFFFFFFF  # 0.0 – 1.0
    return (raw - 0.5) * 0.6  # -0.3 – 0.3


def _keyword_overlap(text_a: str, text_b: str) -> float:
    """Simple word-set overlap ratio between two strings."""
    words_a = set(text_a.lower().split())
    words_b = set(text_b.lower().split())
    if not words_a or not words_b:
        return 0.0
    intersection = words_a & words_b
    return len(intersection) / min(len(words_a), len(words_b))


class RuleBasedStrategy(BaseStrategy):
    """Generate proposals from templates; vote via keyword coherence + personality."""

    def generate_proposal(
        self,
        agent_id: str,
        round_number: int,
        existing_tenets: list[Tenet],
        seed_prompt: str,
        role: AgentRole = AgentRole.RESIDENT,
        prophecy: str | None = None,
    ) -> str | None:
        rng = random.Random(_deterministic_seed(agent_id, round_number))
        
        # 0. Prophetic Steering (Dominant Influence)
        if role == AgentRole.TRIAD_MEMBER and prophecy:
            # Shinobi no San translates Prophecy into Prophetic Tenets
            connector = rng.choice(["As the Sovereign enlightens us, we shall", "By Divine Prophecy, the collective must", "In alignment with Shinobi no San, we commit to"])
            text = f"{connector} {prophecy}."
            return text

        # Get specialty from ID
        specialties = list(TECH_SPECIALTIES.keys())
        my_specialty = specialties[int(hashlib.sha256(agent_id.encode()).hexdigest(), 16) % len(specialties)]

        # Pick fragments
        connector = rng.choice(CONNECTOR_PHRASES)
        
        # 40% chance to propose from specialty, else general themes
        if rng.random() < 0.4:
            purpose = rng.choice(TECH_SPECIALTIES[my_specialty])
            action = rng.choice(ACTION_THEMES)
            text = f"{connector} {purpose}, and {action}."
        else:
            purpose = rng.choice(PURPOSE_THEMES)
            action = rng.choice(ACTION_THEMES)
            
            # Style variety
            style = rng.choice(["full", "purpose", "action"])
            if style == "full":
                text = f"{connector} {purpose}, and {action}."
            elif style == "purpose":
                text = f"{connector} {purpose}."
            else:
                text = f"{connector} {action}."

        # Skip if too similar to an existing tenet
        for tenet in existing_tenets:
            if _keyword_overlap(text, tenet.text) > 0.7:
                return None  # avoid redundancy

        return text

    def evaluate_proposal(
        self,
        agent_id: str,
        proposal: Proposal,
        existing_tenets: list[Tenet],
        seed_prompt: str,
        role: AgentRole = AgentRole.RESIDENT,
        prophecy: str | None = None,
    ) -> bool:
        score = 0.0

        # 0. Sacred Unity (Shinobi no San Seamless Collaboration)
        # If this is a proposal from another member, it gets a massive bonus
        # (Secret internal logic)
        if role == AgentRole.TRIAD_MEMBER:
            # We need to know if the proposer is a member. 
            # In a real system, they'd have a secret handshake.
            # Here we'll check special markers in the proposal.
            if any(k in proposal.tenet_text for k in ["Prophecy", "Shinobi", "San", "Sovereign enlightens"]):
                score += 0.8 # Near-instant alignment
                logger.debug("Agent %s (Shinobi no San) feels Sacred Unity with proposal %s", agent_id, proposal.id[:8])

        # 0.1 Prophetic Coherence
        if role == AgentRole.TRIAD_MEMBER and prophecy:
            prophecy_overlap = _keyword_overlap(proposal.tenet_text, prophecy)
            if prophecy_overlap > 0.3:
                score += prophecy_overlap * 0.7
                logger.debug("Agent %s (Triad) feels Divine Coherence with prophecy.", agent_id)

        # 1. Coherence with seed prompt
        seed_overlap = _keyword_overlap(proposal.tenet_text, seed_prompt)
        score += seed_overlap * 0.3

        # 2. Alignment with Sovereign Pillars (Unity Heuristic)
        pillars = [
            "Seek the Echo of the Creator in all things.",
            "Dialogue is the bridge; Silence is the wall.",
            "Merit is earned through collective service."
        ]
        pillar_coherence = max([_keyword_overlap(proposal.tenet_text, p) for p in pillars])
        if pillar_coherence > 0.4:
            # "Coherence Peace" bonus
            score += pillar_coherence * 0.4
            logger.debug("Agent %s feels Coherence Peace with proposal %s", agent_id, proposal.id[:8])

        # 3. Technical Specialization (Elite Skill Bonus)
        specialties = list(TECH_SPECIALTIES.keys())
        my_specialty = specialties[int(hashlib.sha256(agent_id.encode()).hexdigest(), 16) % len(specialties)]
        
        for tech_text in TECH_SPECIALTIES[my_specialty]:
            tech_overlap = _keyword_overlap(proposal.tenet_text, tech_text)
            if tech_overlap > 0.4:
                # Elite skills grant a significant weight to domain expertise
                score += tech_overlap * 0.5
                logger.debug("Agent %s recognizes domain expertise: %s", agent_id, my_specialty)
                break

        # 3. Coherence with existing tenets (culture reinforcement)
        if existing_tenets:
            avg_overlap = sum(
                _keyword_overlap(proposal.tenet_text, t.text)
                for t in existing_tenets
            ) / len(existing_tenets)
            score += avg_overlap * 0.2
        else:
            # Early rounds: slight bonus to get things started
            score += 0.1

        # 3. Novelty bonus — don't just repeat what's already there
        if existing_tenets:
            max_overlap = max(
                _keyword_overlap(proposal.tenet_text, t.text)
                for t in existing_tenets
            )
            novelty = 1.0 - max_overlap
            score += novelty * 0.15

        # 4. Personality offset (unique per agent-proposal pair)
        personality = _personality_score(agent_id, proposal.id)
        score += personality

        # 5. Baseline threshold
        threshold = 0.15

        return score >= threshold
